apiVersion: v1
kind: Service
metadata:
  name: dev-deployment-service
spec:
  selector:
    app: development-deployment  # Make sure this matches the label selector in your deployment
  ports:
    - protocol: TCP
      port: 8080              # Port to expose the service on
      targetPort: 8080        # The port your container is listening on
  type: LoadBalancer         # Exposes the service externally via a LoadBalancer
